version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeE2E_GitProject0102Project
  gitServerName: srcCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
